---
- include: redhat.yml
  when:
    - ansible_os_family == "RedHat"

- name: "powerline eggs install"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - powerline-status
    - powerline-gitstatus

- name: "ensure needed folders exists"
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /usr/share/fonts/truetype
    - /etc/powerline
    - /etc/powerline/themes
    - /etc/powerline/themes/shell
    - /etc/powerline/colorschemes

- name: "fonts download"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - url: "https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf"
      dest: /usr/share/fonts/truetype/PowerlineSymbols.otf
    - url: "https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf"
      dest: /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf

- name: "fonts install"
  file:
    src: /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf
    dest: /etc/fonts/conf.d/10-powerline-symbols.conf
    state: link

- name: "copy powerline config"
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - "powerline/config.json"
    - "powerline/themes/shell/default.json"
    - "powerline/colorschemes/default.json"

- name: "ensure configuration is sane"
  shell: powerline-lint
  changed_when: false

- name: "enable powerline for bash"
  copy:
    src: powerline-bash.sh
    dest: /etc/profile.d/powerline-bash.sh
    mode: 0755

